### ISSUE TITLE
The `extract()` examples in the vignette don't work

### ISSUE THREAD

**Issue by dvukcevic** [Voltemand/rater#11]
In the **Workflow** vignette, the very last examples show how to use `extract()`.  However, they don't work.  I think we need to explicitly name the second argument as `param`.  For example:

```r
extract(fit, param = "prevalance")
```

**Comment by dvukcevic** [comment]
Also, with reference to my example, note #9!

**Comment by Voltemand** [comment]
Now fixed

Thanks!
