### ISSUE TITLE
Need default option for plot()

### ISSUE THREAD

**Issue by dvukcevic** [Voltemand/rater#8]
At the moment, if a user runs `plot(fit)` on a model fit object, they would get a message saying more input is required, to specify the type of plot desired.

It would be better to have a default option for this so that this command works 'out of the box'.  Perhaps `type = "raters"` would be a good default, given it is the visualisation we use in our hex sticker?

**Comment by Voltemand** [comment]
This has been incorporated in the most recent version. 

Thanks!
